spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.220.163:3316/XunLiManager?characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: xunli@123456
    max-active: 10
    max-idle: 8
    min-idle: 8
    initial-size: 2
    max-wait: 1000
    validation-query: SELECT now()
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      hibernate.jdbc.batch_size: 2000
    thymeleaf:
      mode: XHTML
      cache: false
logging:
  level:
    com.xunli: debug
    org.springframework: info
    org.hibernate: WARN
context:
  listener:
    classes: com.xunli.manager.listener.ApplicationStartupListener
api:
  manager:
    im:
      url: https://eco.taobao.com/router/rest
      appKey: 24634078
      appSecret: f0a06afbc8f284d8c28abd5429114c4d
    imageServer:
      url: http://119.23.220.163:8080/